#!/usr/bin/python
import sys
import pickle

from gpg import Data
from main.Database import Database
from main.Handler import Handler

if __name__ != '__main__':
    sys.exit()

try:
    with open(Database.PATH, 'rb') as f:
        database = pickle.load(f)
        database.new = False
except FileNotFoundError:
    database = Database()

print('-- TBNU notes --')

if database.new:
    print("help msg")

handler = Handler(sys.argv, database)
while True:
    try:
        inp = input('>> ')
        handler.parse_inp(inp) 
    except KeyboardInterrupt:
        print("\nType 'exit' to exit the program")